export type PackSeverity = 'error' | 'warning';
export type PackErrorCode =
  | 'PACK_MANIFEST_MISSING'
  | 'PACK_MANIFEST_INVALID'
  | 'PACK_VERSION_INVALID'
  | 'PACK_DEPENDENCY_MISSING'
  | 'KNOWLEDGE_CONCEPT_INVALID'
  | 'KNOWLEDGE_SOURCE_MISSING'
  | 'KNOWLEDGE_PREREQ_CYCLE'
  | 'KNOWLEDGE_PREREQ_UNKNOWN'
  | 'CURRICULUM_INVALID'
  | 'CURRICULUM_PREREQ_UNKNOWN'
  | 'CURRICULUM_PREREQ_CYCLE'
  | 'PACK_REFERENCE_MISSING'
  | 'OBJECTIVE_INTENT_UNKNOWN'
  | 'OBJECTIVE_NO_CONCEPTS'
  | 'CAPABILITY_GAP'
  | 'BLUEPRINT_WIDGET_UNKNOWN'
  | 'BLUEPRINT_AUDIENCE_MISMATCH';
export interface PackDiagnostic {
  code: PackErrorCode;
  severity: PackSeverity;
  message: string;
}
